###################$
# cfgs for new dataset #
####################$

# args for network
net_avgpool_size: 3
net_heads:
  - 20
  - 6

# args for dataset and dataloader
dataset: 
data_root: 
tfm_size: (32, 32)
tfm_resize: 40
